## Filtering movies
#### Exercise 1 of the [Datacamp](https://www.datacamp.com/tracks/associate-data-scientist-in-python) Associate Data Sci course.

_You work for a production company that specializes in nostalgic styles. You want to do some research on movies released in the 1990's. You'll delve into Netflix data and perform exploratory data analysis to better understand this awesome movie decade!_

#### **Task** 
Perform exploratory data analysis on the netflix_data.csv data to understand more about movies from the 1990s decade.

- What was the most frequent movie duration in the 1990s? Save an approximate answer as an integer called duration (use 1990 as the decade's start year).

- A movie is considered short if it is less than 90 minutes. Count the number of short action movies released in the 1990s and save this integer as short_movie_count.

#### **Data**
The dataset `netflix_data.csv`, has the following column names and descriptions. 

| Column | Description | Column | Description |
|--------|-------------|--|--|
| `show_id` | The ID of the show | `date_added` | Date added to Netflix |
| `type` | Type of show | `release_year` | Year of Netflix release |
| `title` | Title of the show | `duration` | Duration of the show in minutes |
| `director` | Director of the show | `description` | Description of the show |
| `cast` | Cast of the show | `genre` | Show genre |
| `country` | Country of origin | | |

In [5]:
# importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# read in the netflix csv as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")

# show the dataframe to get my bearings 
netflix_df

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,1,A genetics professor experiments with a treatm...,International TV
...,...,...,...,...,...,...,...,...,...,...,...
4807,s7779,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,88,Looking to survive in a world taken over by zo...,Comedies
4808,s7781,Movie,Zoo,Shlok Sharma,"Shashank Arora, Shweta Tripathi, Rahul Kumar, ...",India,"July 1, 2018",2018,94,A drug dealer starts having doubts about his t...,Dramas
4809,s7782,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,88,"Dragged from civilian life, a former superhero...",Children
4810,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...",Sweden,"October 19, 2020",2005,99,When Lebanon's Civil War deprives Zozo of his ...,Dramas
4811,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,111,A scrappy but poor boy worms his way into a ty...,Dramas

In [6]:
# filter the DataFrame for movies released between 1990 and 1999
movies_90s = netflix_df[(netflix_df['type'] == 'Movie') & 
                        (netflix_df['release_year'] >= 1990) & 
                        (netflix_df['release_year'] <= 1999)]

# show revised dataframe
movies_90s

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
6,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",1997,119,After one of his high school students attacks ...,Dramas
118,s167,Movie,A Dangerous Woman,Stephen Gyllenhaal,"Debra Winger, Barbara Hershey, Gabriel Byrne, ...",United States,"April 1, 2018",1993,101,At the center of this engrossing melodrama is ...,Dramas
145,s211,Movie,A Night at the Roxbury,John Fortenberry,"Will Ferrell, Chris Kattan, Dan Hedaya, Molly ...",United States,"December 1, 2019",1998,82,"After a run-in with Richard Grieco, dimwits Do...",Comedies
167,s239,Movie,A Thin Line Between Love & Hate,Martin Lawrence,"Martin Lawrence, Lynn Whitfield, Regina King, ...",United States,"December 1, 2020",1996,108,When a philandering club promoter sets out to ...,Comedies
194,s274,Movie,Aashik Awara,Umesh Mehra,"Saif Ali Khan, Mamta Kulkarni, Mohnish Bahl, S...",India,"June 1, 2017",1993,154,"Raised by a kindly thief, orphaned Jimmy goes ...",Dramas
...,...,...,...,...,...,...,...,...,...,...,...
4672,s7536,Movie,West Beirut,Ziad Doueiri,"Rami Doueiri, Mohamad Chamas, Rola Al Amin, Ca...",France,"October 19, 2020",1999,106,Three intrepid teens roam the streets of Beiru...,Dramas
4689,s7571,Movie,What's Eating Gilbert Grape,Lasse Hallström,"Johnny Depp, Leonardo DiCaprio, Juliette Lewis...",United States,"January 1, 2021",1993,118,"In a backwater Iowa town, young Gilbert is tor...",Classic Movies
4718,s7624,Movie,Wild Wild West,Barry Sonnenfeld,"Will Smith, Kevin Kline, Kenneth Branagh, Salm...",United States,"January 1, 2020",1999,106,"Armed with an ingenious arsenal, two top-notch...",Action
4746,s7682,Movie,Wyatt Earp,Lawrence Kasdan,"Kevin Costner, Dennis Quaid, Gene Hackman, Dav...",United States,"January 1, 2020",1994,191,Legendary lawman Wyatt Earp is continually at ...,Action
4756,s7695,Movie,Yaar Gaddar,Umesh Mehra,"Mithun Chakraborty, Saif Ali Khan, Somy Ali, P...",India,"July 1, 2017",1994,148,When his brother becomes involved in a deadly ...,Dramas

In [7]:
# prepped lists
short = []
standard = []

# loop through rows using .iterrows()
for index, row in movies_90s.iterrows():
    if row['duration'] < 90 and row['genre'] == 'Action':
        short.append(1)
    else:
        standard.append(1)

# total the count of each  
short_movie_count = sum(short)
standard_movie_count = sum(standard)

# use f-strings to print a clear summary
print("Filtering complete...")
print(f"Short movies: {short_movie_count}")
print(f"Standard movies: {standard_movie_count}")

Filtering complete...
Short movies: 7
Standard movies: 176

In [9]:
# the exercise asks for the 'most frequent' movie duration displayed as an integer 
duration = int(movies_90s['duration'].mode().iloc[0])

# the above output made clear to the user
print(f"The most freqeunt movie duration in the 90s was {duration} minutes.")

The most freqeunt movie duration in the 90s was 94 minutes.